### ISSUE TITLE
Provide ways to verify subject name

### ISSUE THREAD

**Issue by winterland1989** [vshabanov/HsOpenSSL#14]
Currently we have to [manually verify certificate's identity](http://hackage.haskell.org/package/tcp-streams-openssl-0.6.0.0/docs/System-IO-Streams-OpenSSL.html#v:connect) with HsOpenSSL, there're two limitations here:

+ We can't use subject alternative name because there's no way to extra it from certificate now.
+ The verification algorithm is hard to implemented correctly.

I'm not sure if openssl provide built-in verification functions, but if it does, i'd like to see it included.

**Comment by vshabanov** [comment]
I'm also don't know whether OpenSSL has these functions. But I will gladly accept a pull request and release new HsOpenSSL on Hackage if anybody is willing to write it.

**Comment by winterland1989** [comment]
It's seems we have to do it manually, [here](http://apidock.com/ruby/OpenSSL/SSL/verify_certificate_identity/class) is how ruby do it. We will want a function to extra extension info from certificate. 

By no means i'm familiar with openssl, so i'm sorry not being able to help : (

**Comment by glguy** [comment]
Modern versions of OpenSSL provide this functionality. I'm binding to it here https://github.com/glguy/irc-core/blob/v2/hookup/src/Hookup/OpenSSL.hsc for my IRC client. The issue with adding it to HsOpenSSL itself would be deciding that it was time to break compatibility with systems that have old versions of OpenSSL installed. Conditionally exposing this functionality isn't a viable option as it can't be expressed by version constraints.

**Comment by vshabanov** [comment]
Thank you for pointing this out.
It seems that OpenSSL 1.1.0 added more simple functions to do it
https://www.openssl.org/docs/man1.1.0/ssl/SSL_set_hostflags.html

Looking at
https://github.com/openssl/openssl/blame/master/crypto/x509/x509_vpm.c
`X509_VERIFY_PARAM_set1_host` function that you use was too added in OpenSSL 1.1.0
https://github.com/openssl/openssl/commit/3bf15e2974f416cb970ef54fae0f600ec299000e

So it should be possible to use conditional 
```
#if OPENSSL_VERSION_NUMBER >= 0x10100000L
...
#endif
```
to implement these functions.

**Comment by glguy** [comment]
The reason I haven't submitted a patch with this functionality made conditionally available is that I don't think that it's appropriate to conditionally export it. If my package depends on HsOpenSSL and uses this functionality I need a way to convey that information to my users. With conditional inclusion users with old versions of openssl will experience build failures without any indiction of how to proceed.

**Comment by vshabanov** [comment]
If user has OpenSSL 1.1.0 then HsOpenSSL will contain necessary functions. If not then you don't get this functionality anyway.

It's possible to use warning pragma:
```
#if OPENSSL_VERSION_NUMBER >= 0x10100000L
X509_VERIFY_PARAM_set1_host :: ...
#else
X509_VERIFY_PARAM_set1_host = error "Please update to OpenSSL 1.1.0" -- or just "return ()"
{-# WARNING X509_VERIFY_PARAM_set1_host "Please update to OpenSSL 1.1.0" #-}
#endif
```
although it could go unnoticed during compilation of package and then package will silently work wrong.

Another option is to make version newtype:
```
#if OPENSSL_VERSION_NUMBER >= 0x10100000L
X509_VERIFY_PARAM_set1_host :: ...
#else
newtype FunctionRequiresOpenSSL1_1_x = FunctionRequiresOpenSSL1_1_x
X509_VERIFY_PARAM_set1_host = FunctionRequiresOpenSSL1_1_x
#endif
```
it leads to more "readable" error message. Although, I think that just requiring OpenSSL 1.1.x somewhere in package description is more right way to go.

**Comment by winterland1989** [comment]
I think a simple conditional definition is fine, it will guarantee your code won't compile if the function is not there. All we need to do is add some haddock to imply this function is conditional defined.
