### ISSUE TITLE
Link Failure on OS X

### ISSUE THREAD

**Issue by sseveran** [vshabanov/HsOpenSSL#20]
I am getting a link time failure on OS X:

    Undefined symbols for architecture x86_64:
      "_DHparams_dup", referenced from:
          _HsOpenSSL_DHparams_dup in libHSHsOpenSSL-0.11.4.4-IwNAgR18rZ2COI1mjG0hrU.a(HsOpenSSL.o)
         (maybe you meant: _HsOpenSSL_DHparams_dup)
      "_X509_CRL_get0_by_serial", referenced from:
          _c16Cf_info in libHSHsOpenSSL-0.11.4.4-IwNAgR18rZ2COI1mjG0hrU.a(Revocation.o)
      "_X509_STORE_CTX_get0_current_crl", referenced from:
          _HsOpenSSL_X509_STORE_CTX_get0_current_crl in libHSHsOpenSSL-0.11.4.4-IwNAgR18rZ2COI1mjG0hrU.a(HsOpenSSL.o)
         (maybe you meant: _HsOpenSSL_X509_STORE_CTX_get0_current_crl)
      "_X509_STORE_CTX_get0_current_issuer", referenced from:
          _HsOpenSSL_X509_STORE_CTX_get0_current_issuer in libHSHsOpenSSL-0.11.4.4-IwNAgR18rZ2COI1mjG0hrU.a(HsOpenSSL.o)
         (maybe you meant: _HsOpenSSL_X509_STORE_CTX_get0_current_issuer)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    `gcc' failed in phase `Linker'. (Exit code: 1)

This only started happening after upgrading to GHC 8 so I am not sure if this is an issue with this library or some other GHC issue.

**Comment by vshabanov** [comment]
Hm, it seems that HsOpenSSL was compiled with OpenSSL 1.1.x but linking with pre 1.1.x OpenSSL version.
Could you attach output of linker with `-v` option and output of `cabal install -v HsOpenSSL`?

**Comment by sseveran** [comment]
I have not had a non-stack environment working on OS X for some time. I was unable to make it work as a statically linked executable but I got it working with dynamic linking. I had to add the homebrew-openssl flag which made it work.
