### ISSUE TITLE
getCipherNames returns an empty list

### ISSUE THREAD

**Issue by arbus** [vshabanov/HsOpenSSL#26]
I am working on a mac (10.11) and have built the library with the following flags:

`stack build --extra-include-dirs=/usr/local/opt/openssl/include --extra-lib-dirs=/usr/local/opt/openssl/lib --flag HsOpenSSL:homebrew-openssl`

The build succeeds but calling `getCipherNames` returns `[]` and `getCipherByName` always returns a `Nothing` regardless of what is passed in. Am I missing something in the setup of the library?

**Comment by vshabanov** [comment]
Unfortunately, it doesn't work for a quite some time and I don't know why.

I will be glad to accept a pull request (or some configuration details in case additional setup is necessary for these functions to work).

**Comment by arbus** [comment]
The problem was that I hadn't wrapped the calls inside a `withOpenSSL`. Works correctly now!
