### ISSUE TITLE
Trouble setting ciphers

### ISSUE THREAD

**Issue by hillaryan** [vshabanov/HsOpenSSL#29]
Here is a snippet of some code I'm testing:
```
c <- SSL.context                                                              
SSL.contextSetCiphers c "DEFAULT"                                               
SSL.contextSetVerificationMode c (SSL.VerifyPeer True True Nothing)           
SSL.contextSetCAFile c ca_file_name
...
```
When I make the connection (via mysql-haskell-openssl), I get `user error (error:140A90A1:lib(20):func(169):reason(161))`. It appears this error indicates that no ciphers are being set. Has anyone experienced this before? 

As part of testing the code, I also changed `SSL.contextSetCiphers c "DEFAULT"` to `SSL.contextSetCiphers c "PIZZA"`. The docs state that "Unrecognised ciphers are ignored. If no ciphers from the list are recognised, an exception is raised." PIZZA isn't a valid cipher, yet I get the same `reason(161)` error when trying to connect rather than the exception I'm expecting. Any thoughts here?

**Comment by vshabanov** [comment]
Have you called `withOpenSSL` before to initialize OpenSSL?

**Comment by hillaryan** [comment]
That did it! I figured since `mysql-haskell-openssl` called `withOpenSSL` during `connect`, I didn't need to call that when I set up the context, but turns out I was wrong. Thank you so much for your quick response!
