### ISSUE TITLE
installation on windows 8.1

### ISSUE THREAD

**Issue by vtashkov** [vshabanov/HsOpenSSL#33]
The package can not be installed under Win 8.1 (and probably others), since it has dependency on SSL and none of the current versions of OpenSSL is compatible. Even after manual tuning the file names of the libraries, after which it built, then it gives run-time error on the basic example in the documentation (which by the way is invalid syntactically at least in GHC 8.02). I am a noob in this and probably am missing something, but there is no info anywhere.

**Comment by vshabanov** [comment]
Do you use MinGW or Cygwin? I'm not sure that HsOpenSSL will build with in other contexts.

And could you point what example is syntactically invalid?

**Comment by vtashkov** [comment]
Forgive me my incompetence, but I believe that I do not build it from source, I am just using stack install for that and it doesn't work with OpenSSL libraires out of the box, even though I add --extra-include-dir and --extra-lib-dir. Then I needed to change the name of the dll to be libssl.dll (I am using 64 bit windows 8.1), while it is something like libssl-1-1-x64 by default. In this case it builds, but then when you try even to open a connection there are some weird exceptions.

**Comment by vtashkov** [comment]
About the invalid syntax:
`receiveResponse c (\p i -> do
        xm <- Streams.read i
        case xm of
            Just x    -> S.putStr x
            **Nothing   ->"")`**

Here it needs to be something like S.putStr "", instead of just empty string.

**Comment by vshabanov** [comment]
Hm. I don't see this example anywhere in HsOpenSSL repository. Where did you get it?

I'm afraid I can't help much with stack (and Windows in general). I suspect that you should use MinGW (or Cygwin) to use HsOpenSSL in Windows. Or maybe try to use libssl built with different calling convention (ccall instead of stdcall or vice versa).

**Comment by vshabanov** [comment]
Oh, and don't forget to use `withOpenSSL`

**Comment by vtashkov** [comment]
My bad, the example was actually from [http-streams](https://hackage.haskell.org/package/http-streams-0.8.5.3/docs/Network-Http-Client.html) library.
In any case, thank you for your time!

**Comment by vtashkov** [comment]
I have found a solution to the problem, so I'll write it here in case someone has the same. This is an installation on 64 bit Windows 8.1, using stack.
First, you need to install Win64 OpenSSL v1.0.2L (NOT Light) from [here](https://slproweb.com/products/Win32OpenSSL.html). Accordingly, if you are on 32 bit system, you should use Win32 OpenSSL, but I think that in 32 bit version there is no problem building. Let's say that it's installed in C:\OpenSSL-Win64 .
Second, you need to **copy** C:\OpenSSL-Win64\libssl32.dll to the same location as libssl.dll.
Third, you need to add to stack command for installation the parameters --extra-include-dirs=C:\OpenSSL-Win64\include --extra-lib-dirs=C:\OpenSSL-Win64

**Comment by alogic0** [comment]
I've been installing on Windows 7 from the `mingw64` shell and this worked for me.
```bash
pacman -Sy mingw-w64-x86_64-openssl
cabal get HsOpenSSL-0.11.4.14
cd HsOpenSSL-0.11.4.14
cabal install --user --extra-include-dirs=/mingw64/include --extra-lib-dirs=/mingw64/lib --extra-lib-dirs=/mingw64/bin
```
