### ISSUE TITLE
Cabal Install Failure

### ISSUE THREAD

**Issue by nick-chandoke** [vshabanov/HsOpenSSL#36]
When I try cabal install, I get dieVerbatim: user error (cabal: Couldn't parse the output of 'setup register
--gen-pkg-config':NoParse
"license" 5
)
I'm not experienced with cabal...frankly I can't decipher this at all.

**Comment by glguy** [comment]
@nick-chandoke You might need to update your *cabal-install* executable. The current version is 2.2.0.0

**Comment by nick-chandoke** [comment]
@glguy You were correct! Thank you.

**Comment by vshabanov** [comment]
It's interesting to know precise version where it was fixed. Cabal 2.x is used with GHC 8.2.1+ but HsOpenSSL works with earlier GHC versions too and I don't like to break compatibility.
