### ISSUE TITLE
Allow network-2.7.0.0

### ISSUE THREAD

**Issue by glguy** [vshabanov/HsOpenSSL#37]
There's a new version of network out. I'd be nice to revise the bounds to allow it. There doesn't appear to be any change that negatively impacts HsOpenSSL

**Comment by vshabanov** [comment]
Fixed in `HsOpenSSL-0.11.4.14`

**Comment by glguy** [comment]
Discarding the upper bounds altogether is just introducing future breakage. A new version wasn't even needed, we can revise upper bounds in place on Hackage.

**Comment by vshabanov** [comment]
Keeping upper bounds introduces even more breakages (I'm a bit tired from stackage tickets) and I don't think that bytestring, network and time will significantly change their API.

Hard to say which is better -- relying on old package and break build of other newer packages or break own build. At the moment first case appears more frequently.

Could you add upper bounds if they're not exists on Hackage in case of build failure?
