### ISSUE TITLE
Inaccurate/missing version bounds in HsOpenSSL-0.11.4.15, HsOpenSSL-0.11.4.14 and others

### ISSUE THREAD

**Issue by hvr** [vshabanov/HsOpenSSL#41]
See https://matrix.hackage.haskell.org/package/HsOpenSSL@1547912005

In my function as Hackage Trustee I've already fixed up the metadata of the affected releases

 - https://hackage.haskell.org/package/HsOpenSSL-0.10.1.3/revisions/
 - https://hackage.haskell.org/package/HsOpenSSL-0.10.1.4/revisions/
 - https://hackage.haskell.org/package/HsOpenSSL-0.10.2/revisions/
 - https://hackage.haskell.org/package/HsOpenSSL-0.10.2.1/revisions/
 - https://hackage.haskell.org/package/HsOpenSSL-0.10.3/revisions/
 - https://hackage.haskell.org/package/HsOpenSSL-0.10.3.1/revisions/
 - https://hackage.haskell.org/package/HsOpenSSL-0.10.3.2/revisions/
 - https://hackage.haskell.org/package/HsOpenSSL-0.10.3.3/revisions/
 - https://hackage.haskell.org/package/HsOpenSSL-0.10.3.4/revisions/
 - https://hackage.haskell.org/package/HsOpenSSL-0.10.3.5/revisions/
 - https://hackage.haskell.org/package/HsOpenSSL-0.10.3.6/revisions/
 - https://hackage.haskell.org/package/HsOpenSSL-0.10.4/revisions/
 - https://hackage.haskell.org/package/HsOpenSSL-0.10.5/revisions/
 - https://hackage.haskell.org/package/HsOpenSSL-0.11/revisions/
 - https://hackage.haskell.org/package/HsOpenSSL-0.11.1/revisions/
 - https://hackage.haskell.org/package/HsOpenSSL-0.11.4.14/revisions/
 - https://hackage.haskell.org/package/HsOpenSSL-0.11.4.15/revisions/

This has started to propagate to other packages which are reverse dependencies and resulting in breaking build-plans for those packages until it was rectified via a metadata revision.

We need your help! Please help us ensure a good user experience for users of Hackage/Cabal by the use of the  PVP mandated upper bounds in order to reduce the penalty on the Hackage infrastructure  as well as to avoid unnecessary extra work for you as well as for us Hackage Trustees!

**Comment by vshabanov** [comment]
Latest version builds fine with `network-3.0.0`. I'm not sure about specifying upper version bounds. I've removed them precisely because of `HsOpenSSL` could not build with new versions of `network`. And it required only few lines of code (#40) to support major `network` update.

**Comment by vshabanov** [comment]
OK. I've added upper bounds to all dependencies and updated package metadata.
