### ISSUE TITLE
Add SSL_CTX_set_session_id_context

### ISSUE THREAD

**Issue by fgaz** [vshabanov/HsOpenSSL#55]
As in the title, it'd be nice to have a binding to SSL_CTX_set_session_id_context too. Without it, it's impossible to enable server session resumption with client certificates.

Would you accept a PR that adds a `contextSetSessionIdContext :: SSLContext -> ByteString -> IO ()` function?

**Comment by vshabanov** [comment]
Sure, I will accept a PR and publish new version on Hackage.
